# 
# This workflow contains jobs to test and build the application
# 
name: Build

on:
  push:
  pull_request:
    branches: 
      - master

jobs:
  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: dart --version
    - run: flutter --version
    - run: flutter pub get
    - run: flutter test
